### ISSUE TITLE
What about source map?

### ISSUE THREAD

**Issue by ardi-n** [HuasoFoundries/systemjs-less-plugin#6]
This is new after recent changes. less-builder.js complains because sourceMap option was changed to false:

```
Trace: [TypeError: Cannot read property 'toString' of undefined]
    at eval (file:///Users/***/Documents/EP-trunk/jspm_packages/github/HuasoFoundries/systemjs-less-plugin@1.6.1/less-builder.js:93:13)
```

When I manually changed `sourceMap: false` to `sourceMap: outputOpts.sourceMaps` then this happened:

```
Trace: { [Error: Cannot find module 'source-map']
  message: 'Cannot find module \'source-map\'',
  stack: 'Error: Cannot find module \'source-map\'\n    at Function.Module._resolveFilename (module.js:336:15)\n    at Function.Module._load (module.js:286:25)\n    at Module.require (module.js:365:17)\n    at require (module.js:384:17)\n    at Object.getSourceMapGenerator (/Users/***/Documents/EP-trunk/jspm_packages/github/less/less.js@2.6.1/lib/less-node/environment.js:12:16)\n    at new SourceMapOutput (/Users/***/Documents/EP-trunk/jspm_packages/github/less/less.js@2.6.1/lib/less/source-map-output.js:25:59)\n    at SourceMapBuilder.toCSS (/Users/***/Documents/EP-trunk/jspm_packages/github/less/less.js@2.6.1/lib/less/source-map-builder.js:8:31)\n    at ParseTree.toCSS (/Users/***/Documents/EP-trunk/jspm_packages/github/less/less.js@2.6.1/lib/less/parse-tree.js:33:47)\n    at /Users/***/Documents/EP-trunk/jspm_packages/github/less/less.js@2.6.1/lib/less/render.js:31:40\n    at /Users/***/Documents/EP-trunk/jspm_packages/github/less/less.js@2.6.1/lib/less/parse.js:63:17\n    at Object.finish [as _finish] (/Users/***/Documents/EP-trunk/jspm_packages/github/less/less.js@2.6.1/lib/less/parser/parser.js:183:28)\n    at Object.ImportVisitor._onSequencerEmpty (/Users/***/Documents/EP-trunk/jspm_packages/github/less/less.js@2.6.1/lib/less/visitors/import-visitor.js:35:14)\n    at ImportSequencer.tryRun (/Users/***/Documents/EP-trunk/jspm_packages/github/less/less.js@2.6.1/lib/less/visitors/import-sequencer.js:50:14)\n    at /Users/***/Documents/EP-trunk/jspm_packages/github/less/less.js@2.6.1/lib/less/visitors/import-sequencer.js:19:25\n    at fileParsedFunc (/Users/***/Documents/EP-trunk/jspm_packages/github/less/less.js@2.6.1/lib/less/import-manager.js:50:17)\n    at /Users/***/Documents/EP-trunk/jspm_packages/github/less/less.js@2.6.1/lib/less/import-manager.js:113:21' }
    at eval (file:///Users/***/Documents/EP-trunk/jspm_packages/github/HuasoFoundries/systemjs-less-plugin@1.6.1/less-builder.js:93:13)
```

**Comment by ffflabs** [comment]
It seems the problem happens because the  _optional dependency_ `source-map` (see [less package.json](https://github.com/less/less.js/blob/master/package.json#L50)). It turns out npm's optional dependencies are installed unless you explicitly ask it not to.

Anyway, I'm publishing version @1.7.0 that will do three things:
- Adds less and source-map as optional dependencies. Of course, this shouldn't have any effect when you install system-less-plugin through jspm, but it will point users to the right direction.
- During build, it will check if less is installed as node module. If it is, it will use that one, and enable source map support.
- If the former is false, it will try to load less with jspm, and disable source maps unless the package `source-map` is installed as a node module. Otherwise, I just can't make jspm-version-of-less find its source map sibling.

**Comment by ffflabs** [comment]
Have you tried the Last release? I need your feedback to close this issue

**Comment by ardi-n** [comment]
Sorry for the delay. I've just checked the new release and I didn't notice any problems. Thanks!
